### ISSUE TITLE
Add get_object to crud.get

### ISSUE THREAD

**Issue by seet61** [tarantool/crud#100]
```
# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

```
# tarantool -version
Tarantool 2.5.2-60-g46d2ddf
Target: Linux-x86_64-RelWithDebInfo
```

dependencies = {
     'tarantool',
    'lua >= 5.1',
    'checks == 3.0.1-1',
    'cartridge == 2.3.0-1',
    'metrics == 0.5.0-1',
    'cartridge-cli-extensions == 1.0.0-1',
    'crud',
}

```
crud.get("msisdn_statuses", "123").rows[1]:tomap()
---
- error: '[string "return crud.get("msisdn_statuses", "123").row..."]:1: attempt to
    call method ''tomap'' (a nil value)'

```

Please add functionality like for box.tuple https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_tuple/#box-tuple-tomap

**Comment by akudiyar** [comment]
Proposal: add new method get_object which calls utils.unflatten_rows internally.

**Comment by DifferentialOrange** [comment]
Refer to https://github.com/tarantool/crud/issues/367
