### ISSUE TITLE
If space is sharded by custom field and bucket_id is not specified by user then crud.get should raise an error or do clusterwide query.

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/crud#104]
After https://github.com/tarantool/crud/issues/46 an ability to specify bucket_id was added, but some problems with API still remain.

Now CRUD will try to calculate bucket_id using PK and return an empty resultset.

There are such possible options:
1 do clusterwide (map-reduce) query in such case;
2 add a note to README that if sharding is done by custom field and bucket_id is not specified by user then crud.get will not work as expected.
3 detect that space is not sharded by PK and throw an exception if bucket_id is not specified

**Comment by Totktonada** [comment]
If bucket_id is not specified, crud assumes sharding by the primary key.

After #27 we'll extend this behaviour: if another sharding key is set in tarantool/ddl, crud will use it. If not, we'll keep old behaviour: sharding by the primary key.

So the recommendation will be the following: set full schema in tarantool/ddl to avoid any unexpected outcomes.

Whether it'll solve your problem?

**Comment by vrogach2020** [comment]
@Totktonada looks like we can close this issue after #27 is done.

**Comment by Totktonada** [comment]
So I'll consider it as resolved.
