### ISSUE TITLE
crud.pairs and crud.select hang when selecting tuples by jsonpath index

### ISSUE THREAD

**Issue by akudiyar** [tarantool/crud#106]
Consider a space with a field of type 'map' and a secondary index over a nested field:

```lua
appeals = box.schema.create_space('appeals', { format = {
    { name = 'session_id', type = 'uuid', is_nullable = false },
    { name = 'agent', type = 'map', is_nullable = true },
}})
appeals:create_index('primary', {
    parts = { 'session_id' },
    if_not_exists = true
})
appeals:create_index('agent_id', {
    parts = { { field = 'agent', type = 'string', path = '.agent_id' } },
    unique = false,
    if_not_exists = true
})
```

When trying to select tuples directly via box API on the storages, it works as expected:

![image](https://user-images.githubusercontent.com/2381032/103279918-16dcc080-49e0-11eb-94ba-5b042dfe770a.png)

When trying to select via CRUD API on a router, the request hangs:

```lua
crud.select('appeals', { { '==', 'agent_id', 'denis.tulupov' } }, { use_tomap = true })
```

**Comment by akudiyar** [comment]
The request hangs on waiting for something to appear in the internal iterator channel: https://github.com/tarantool/crud/blob/aba6f9d5cd45d5e3a79a87563293cc04b1c8c6a4/crud/select/iterator.lua#L149

**Comment by mRrvz** [comment]
Should have been fixed with the [introduction of support for jsonpath indexes](https://github.com/tarantool/crud/pull/158). I tested it locally on such a space, everything is ok.
