### ISSUE TITLE
Implement hard limits

### ISSUE THREAD

**Issue by olegrok** [tarantool/crud#131]
Currently user occasionally could run fullscan query and hang storage.

Seems we need to implement some kind of limits - some reasonable restrictions for user queries. Scan not more than 1k tuples and returns not more than 500 tuples.

Of course such limits should be configured anyhow. Maybe clusterwide config in case of cartridge role usage and some options otherwise.

**Comment by unera** [comment]
The problem has already solved twice

- too long processes will be interrupted (see slice)
- select(nil) will warn message

So the ticket can be done.
