### ISSUE TITLE
Hide "bucket_id" field from user

### ISSUE THREAD

**Issue by olegrok** [tarantool/crud#15]
I don't thing it's OK to show our internals for users. I was confused to see that insert returns "bucket_id".

https://github.com/tarantool/crud#insert

Actually I can do nothing with such information. For performance reasons we could return this field when work with raw tuple, but I see no reasons to preserve it in result object.

**Comment by knazarov** [comment]
There is a feature in Tarantool that's called "system fields" (https://github.com/tarantool/tarantool/issues/3985) , which will help solve this. Until then I propose to forget about it.

**Comment by no1seman** [comment]
Suggested solution:
1. Remove bucket_id from data and metadata by default.
- for simple operations - rigth before return. Remove will be done on router for both data and metadata.
- for select and pairs - in low level functions on storage.
2. Add new option (show_bucket_id) to all top level functions (propagate this option to low level ones if needed) to give an ability to NOT remove bucket_id form data and metadata.

PR for simple operations:
https://github.com/tarantool/crud/pull/48

**Comment by no1seman** [comment]
> Hi! Thanks for your patch.
> 
> Unfortunately, currently I have more questions than answers. 
> 
> * Call table.remove for each tuple just decrease general performance of each query (especially of select). Therefore it's quite strange do enable this feature it by default. 
> 
> * In future it will be really box.tuples (after merger and key_def will be ported to Tarantool 1.10). So we will need to call tuple:truncate() for each tuple. So it will be even worse for performance.
> 
> * We won't be able to create formatted tuples because format can't be created we could only use "_format_cdata" provided by schema from connection. 
> 
> Finally, my idea was relevant when we worked with unflattened objects - the cost of actions to hide some field wasn't so high. Currently it's not so.
> 
> _Originally posted by @olegrok in https://github.com/tarantool/crud/pull/48#issuecomment-704676187_

# Task description

By default every CRUD methods:
    - Simple methods:
        - crud.delete()
        - crud.delete_object()
        - crud.get()
        - crud.get_object()
        - crud.insert()
        - crud.insert_object()
        - crud.update()
        - crud.update_object()
        - crud.upsert()
        - crud.upsert_object()
        - crud.replace()
        - crud.replace_object()
    Complex methods:
        - crud.select()
        - crud.pairs()

have to return tuple or set of tuples and metadata without bucket_id (and possibly without any other "system specific" fields). But in some cases it will be usefull to have "system specific" in data and metadata sets.
Shortly we need to have an ability to control if crud methods return bucket_id field (and any other "system specific" fields) or not return.

## Mode change interface variants

There are three options to perform mode changing

### Globally for whole module

In that case we may simply add global variable to _G or use option of crud.init:

```lua
crud.init({show_system_fields = true or false}) -- show_system_fields = false by default
```

### Locally, inplace

Use option in every CRUD methods:

```lua
crud.xxxxxxx(..., {show_system_fields = true or false}) -- show_system_fields = false by default
```

## Shrink "system specific" fields for Simple methods

### Rigth before return (on router)

In that case we can simply remove "system specific" fields right before return the result using table.remove if show_system_fields ~= true:

```lua
table.remove(tuple, bucket_id_index)
table.remove(metadata, bucket_id_index)
```

### Separately (metadata on router and tuple on storage)

In that case we need to propagate show_system_fields state to "storage" and using ```tuple:transform()``` remove "system specific" fields:

```lua
    tuple:transform(bucket_id_index, 1)
```

Metadata can be deleted same as in previous case using ```table.remove(metadata, bucket_id_index)```
In that case we need to calculate bucket_id_index on both router and storage

## Shrink "system specific" fields for Complex methods

In that case we have to propagate show_system_fields flag to Iterator and underlying methods and shrink tuple on every read on storage using ```tuple:transform()```

```lua
    tuple:transform(bucket_id_index, 1)
```

Shrinking metadata have to be made during Iterator initialisation using table.remove(metadata, bucket_id_index) cause Iterator has space_format field which used in underlying methods using ```table.remove(metadata, bucket_id_index)```

So, need to decide the best choise for now to perform functionality Any ideas?

**Comment by knazarov** [comment]
I put a veto on this. We don't want to hide `bucket_id` fields because they are part of the schema, and also because hiding them will slow down the router significantly.

**Comment by knazarov** [comment]
Plus, I think we should encourage smarter connectors to fill `bucket_id` correctly when they create the tuple on their side. This way we may just pass the tuple through to the storage without re-packing it.

**Comment by olegrok** [comment]
I proposed to do it before we started to return result as tuples. It was quite easy to just nullify `bucket_id` field, now it's not so.

Let's just close this issue.

**Comment by Totktonada** [comment]
It seems, there was agreement to don't do that, so I'll close the issue. If someone has an opposite opinion and want to argue, feel free to reopen with reasoning.
