### ISSUE TITLE
Change default hash function to mpcrc32

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/crud#185]
### Motivation

As we know, the current sharding function does not work correctly in a number of cases. This is described here tarantool/vshard#207. But changing the hash function will affect the work of current users who want to upgrade to a newer version of the crud module.

### Solution
We chose the following from the options discussed in the chat:

By default, СRUD version 1.0 will use `mpcrс32`. 

For users who already use CRUD and want to update, we will add the option `use_old_hashfunc`. To use the old hash function, you will need to write in your code `require('crud').USE_OLD_HASHFUNC = true` before `cartridge.cfg` call.

```lua
require('crud').USE_OLD_HASHFUNC = true
cartridge.cfg({ roles = { 'crud-router', 'crud-storage' })
```

Also, we can print a warning in the console about `strcrc32` problems.

Didn't forget about:
- [ ] Introduce this option in Changelog

**Comment by Totktonada** [comment]
A user may experience a problem with strcrc32 when bucket_id is calculated differently for 'logically same' keys, such as `1`, `1LL` and `1ULL`. I don't see other similar cases aside integral numbers.

Let's introduce a terminology here: each integral number has a canonical representation is Lua: it is 'number' Lua type for numbers in the [-10^14+1; 10^14-1] range, cdata<int64_t> for negative numbers outside this range and cdata<uint64_t> for positive numbers outside this range. (See also the decoding part on [this](https://github.com/tarantool/conf/blob/e1da1194fd247405e909a76127e31e0866efc179/conf/client/etcd/scalar_serializer.lua#L134-L152) schema.)

All decoders in tarantool (msgpack, json, yaml) decode integral numbers into the canonical form. It is not easy to get an integral number in a non-canonical form if you don't do this intentionally.

Another point: even if one use a non-canonical number form for calculating bucket_id, (s)he likely do it uniformly as for DML as well as for DQL. So all request types should work as expected in the case. The only problem is that such code requires extra attention from a developer.

Everything above is said just to show that impact of the problem should not be large. While changing the default sharding function may affect much more users: it'll change how bucket_id is calculated for all keys in all usage scenarious.

Until I'll see at least one motivating case, I'll on the position that we should not change the default (even despite that it has known problems).

----

Aside of 'keep strcrc32' and 'move to mpcrc32', there is another option: 'canonicalize integral numbers before passing to strcrc32'.

I don't think that we should do it anyway, just noted.

**Comment by artur-barsegyan** [comment]
I close this task until we understand how this can affect users.
