### ISSUE TITLE
Add batch insert/upsert/insert_objects/upsert_objects

### ISSUE THREAD

**Issue by no1seman** [tarantool/crud#193]
When perform huge cold data loading it willbe great to have an availability of inserting/upserting data by batches (list of tuples/objects). This functions will be called directly from cartridge-java or any other clients.

**Comment by olegrok** [comment]
Related to https://github.com/tarantool/vshard/issues/176

**Comment by unera** [comment]
both

**Comment by no1seman** [comment]
I should say that this task is not so easy as may seems to be. First of all @olegrok mentioned some additional functinality we need in vshard, also need to support this feature in some popular language connectors: Java/Go/python ... The main problem is how to report caller about successed or failed operations from the batch. Seems this feature must be additionally triaged

**Comment by Totktonada** [comment]
We can implement batching without cluster wide consistency guarantees for now (it requires 2PC, distributes transactions or something of this kind), but with detailed reporting about errors. Is there a need in such step toward?

**Comment by denesterov** [comment]
There is another use case, much more common (and, I think, important) than bulk operations.

If you have a *slightly* complex data structure, not just Key/Document, you are in trouble with crud.

For example, we have an customer record in one space and his orders in second space, both sharded identically. Lets say we need to close one order and create another in one move, or just store customer record with all his orders at once, not interlacing with other changes / read operations.

CRUD cannot do this.

**Comment by akudiyar** [comment]
@denesterov 

>For example, we have an customer record in one space and his orders in second space, both sharded identically. Lets say we need to close one order and create another in one move, or just store customer record with all his orders at once, not interlacing with other changes / read operations.

I have a proposal of function registration API as a basis for implementing such cases: #80
