### ISSUE TITLE
Parameterize regression test suite with DDL sharding key

### ISSUE THREAD

**Issue by ligurio** [tarantool/crud#208]
parameterization is coming to luatest [1], it would be nice to parameterize the whole test suite with an option that enables/disables custom sharding key to make sure that everything is fine.

1. https://github.com/tarantool/luatest/pull/163

**Comment by Totktonada** [comment]
The sharding keys support comes with tests (PR #181), so I guess here you propose to coalesce the similar tests cases. My thoughts on the topic are below.

1. It is hard to verify that we don't miss some cases if we'll do a massive tests rewritting.
2. Those new tests will be more abstract and less straighforward.
3. It is considerable amount of thorough work.
4. However if we'll define a set of simple tests that can be written in an abstract way and run against different schemas, we can easily add a new case to verify against all those schemas.

I found the idea of using parametrization in new tests, where it is appropriate, nice. But I doubt about rewriting of existing tests. However I'm not the author of tests, so my judgement may be a bit too abstract.

@ligurio, what do you think here?

**Comment by ligurio** [comment]
I agree. Feel free to close the issue.

**Comment by Totktonada** [comment]
Closing then. // CC @DifferentialOrange
