### ISSUE TITLE
Create a test with comparison vshard.call() and CRUD performance

### ISSUE THREAD

**Issue by ligurio** [tarantool/crud#225]
CRUD uses `vshard.call()` for executing CRUD operations on storage. It would be interesting to compare running, for example, SELECT and INSERT via `vshard.call()` and `crud:select()` and `crud:insert()`. Comparison will show us an overhead that CRUD adds to operations on storage.

The outcome of the task is a test with at least inserts and selects using `vshard.call()` and CRUD.

**Comment by Totktonada** [comment]
NB: Consider the test case provided by Dmitry in #220. I measured PR #222 and PR #226 using it.
