### ISSUE TITLE
Calls to routers and storages when crud-router and crud-storage roles initialization is not finished yet

### ISSUE THREAD

**Issue by savinov** [tarantool/crud#229]
There are exceptions trown in cartridge-java driver due to crud-router and crud-storage roles initialization issues.

How to repoduce:
- run some load test to call crud.select (with prefer_replica=true and balance=true) and crud.upsert
- stop/start a few routers
- stop/start a few replicas (not leaders) in replicasets

Result for select:
```
org.springframework.dao.DataRetrievalFailureException: InnerErrorMessage:
code: 33
message: Procedure '_crud.select_on_storage' is not defined; nested exception is io.tarantool.driver.exceptions.TarantoolInternalException: InnerErrorMessage:
code: 33
message: Procedure '_crud.select_on_storage' is not defined
```
Result for upsert:
```
Caused by: io.tarantool.driver.exceptions.TarantoolInternalException: InnerErrorMessage:
code: 32
message: ...example.lua:100: variable 'crud' is not declared
```

**Comment by savinov** [comment]
SDK version: Tarantool Enterprise 2.7.3-0-gdddf926c3-r428
Cartridge version: 2.7.2
CRUD version: 0.9.0

**Comment by Totktonada** [comment]
The problem with storages should be generally resolved after https://github.com/tarantool/vshard/issues/298, however we can implement some simple retrying strategy in crud even without this feature.

The problem with routers should be resolved by https://github.com/tarantool/cartridge-java/issues/159 and, sadly, there is nothing that we can fix on the crud side.

**Comment by R-omk** [comment]
Same problem solved in vshard https://github.com/tarantool/vshard/issues/123
