### ISSUE TITLE
Allow change default shard func

### ISSUE THREAD

**Issue by R-omk** [tarantool/crud#247]
> By default CRUD calculates bucket ID using primary key and a function vshard.router.bucket_id_strcrc32(key),

In addition to adding the ability to change the shard function, it should be explained to new users why using the default value (strcrc32) is a bad idea.

**Comment by Totktonada** [comment]
@R-omk Good idea, I would do it in the scope of #237.

BTW, do you know effects aside of ones described [here](https://github.com/tarantool/crud/issues/185#issuecomment-886894723), about which we should warn users?

**Comment by Totktonada** [comment]
#237 is implemented and released in [crud 0.11.0](https://github.com/tarantool/crud/releases/tag/0.11.0). The guides are in the readme. Feel free to reopen the issue if you think we should add something here.
