### ISSUE TITLE
[1pt] Refactor `limit` option

### ISSUE THREAD

**Issue by dokshina** [tarantool/crud#25]
* Rename `limit` -> `first`
* Support negative values of `first`:
    * For `{1, 2, 3, 4, 5, 6}` select w/ options `{after = 5, first = -2}` returns `{3, 4}` (XXX: how should it work for `pairs`?)
    * Deny to use negative `first` w/o `after`

**Comment by tsafin** [comment]
This rename looks unnecessary. From external prospective (IMVHO) limiting resultset with `limit` is much more expected than `first`. Why do we want to rename it here?

**Comment by mtrempoltsev** [comment]
This is needed to unify terminology with TDG

**Comment by akudiyar** [comment]
I have the same question -- "limit" is more recognizable in the outer world.

**Comment by knazarov** [comment]
Let me settle this. It's a matter of preference, so we'll do "first" instead of "limit".
