### ISSUE TITLE
Write in log when see `select(nil)`

### ISSUE THREAD

**Issue by kyukhin** [tarantool/crud#276]
Extracted from https://github.com/tarantool/tarantool/issues/6539

After internal discussion, we decided:
- Warn the user about potentially dangerous code
- With logging level - CRIT
- For all cases:
     - `crud:select()`
     - `crud:select(nil)`
     - `crud:select{}`
- With ratelimit (it's worth raising it higher than 0.5 sec for this particular case)
- Add the option fullscan=true to suppress the message in the log

**Comment by Totktonada** [comment]
How it is implemented in tarantool: https://github.com/tarantool/tarantool/pull/7064. (At the moment of writing this, the pull request is in review and things may change.)

**Comment by oleg-jukovec** [comment]
Requirements have been updated:

https://github.com/tarantool/tarantool/issues/7129
