### ISSUE TITLE
Implementation of getting space schema via crud

### ISSUE THREAD

**Issue by GRISHNOV** [tarantool/crud#293]
As part of implementation [task](https://github.com/tarantool/tt/issues/35) `tt crud import`, there is a need to get a space data schema.

Using [`ddl.get_schema()`](https://github.com/tarantool/ddl#get-spaces-format) does not always give the desired result, since in `ddl` case the scheme is taken locally from the router, and not from the storages. Also, the `ddl` module in the general case may not be present on the router.

It is proposed to implement an analogue of `ddl.get_schema()` in crud

**Comment by Totktonada** [comment]
I think more on it and I have an idea here.

We need the database schema in `tt crud import` to map CSV columns (their names or ordinals) to tuple fields (via field names or directly to field numbers). So we can consider the following facts:

1. We need a schema for a particular space, not necessary for all existing ones.
2. We need only space format information (field names) and we're not not interested in indexes and sharding metainfomation.

So we can just do `crud.select(space_name, nil, {first = 0})` and look into the `metadata` field in the return value.

There is even a simple test that verifies that `first = 0` is valid:

https://github.com/tarantool/crud/blob/d497322fcb079369d715fdb6af14b314155cb6b1/test/integration/select_test.lua#L168-L174

@GRISHNOV, @LeonidVas, whether this solution suits you?

**Comment by Totktonada** [comment]
It seems that the proposed approach is suits all needs of https://github.com/tarantool/tt/issues/35. Feel free to reopen the issue if I'm not right.
