### ISSUE TITLE
получить возможность прочитать документ не целиком, а только часть

### ISSUE THREAD

**Issue by ext0404** [tarantool/crud#324]
ищу возможность в cartridge (crud ?) прочитать документ не целиком, а только часть
допустим, кортеж хранит в поле структуру типа map, которая достаточно большая. Упрощенный пример кортежа: id = 1, map = { "a": 1, "b": {"c": 2, "d": 3}}
я вижу, что есть возможность фильтровать в crud.select по полям мапы:

crud.select("test", '==', 'pk', 1},{'==', 'map.b.c', 2)

выражение map.b.c а-ля json-path применяется для фильтрации, но не применяется, будучи заданным в opts.fields, то есть потенциально большой документ всегда будет гоняться по сети, хотя нужно взять только его фрагмент:

crud.select("test", '==', 'field1', 1},{'==', 'map.b.c', 1, {fields={'map.b.c'}})
—

null
line: 480
class_name: FilterFieldsError
err: Space format doesn't contain field named "map.b.c"
file: '...0920-151853/.rocks/share/tarantool/crud/common/utils.lua'
str: 'FilterFieldsError: Space format doesn''t contain field named "map.k3.c1"'
...
есть ли возможность получить только часть документа, и не ошибка ли это ? и в select-conditions, и в opts.fileds передаются "поля", но в одном случае это могут быть выражения типа a.b.c, а в другом - нет

**Comment by R-omk** [comment]
duplicate  https://github.com/tarantool/crud/issues/120
