### ISSUE TITLE
[4pt] Investigate merger/key_def embedding into current implementation

### ISSUE THREAD

**Issue by olegrok** [tarantool/crud#33]
Write test branch for 2.4+ Tarantool versions until https://github.com/tarantool/tarantool/issues/5273 and https://github.com/tarantool/tarantool/issues/5384 are not implemented

**Comment by olegrok** [comment]
See https://github.com/Totktonada/tarantool-merger-examples/tree/master/chunked_example_fast

**Comment by Totktonada** [comment]
I would be interested in performance testing results.

A measurement may be more close to a real life if we would imitate a delay between a router and a storage:

```sh
tc qdisc add dev lo root handle 1:0 netem delay 500msec  # 1ms rtt
tc qdisc del dev lo root  # clean up
```

However microbenchmark is interesting too.

**Comment by olegrok** [comment]
I have simple benchmark - https://github.com/tarantool/crud/tree/perf-test

But at first glance I see some slowdown after merger integration (introduced here https://github.com/tarantool/crud/pull/38).
Seems we need to cache key_def instances (Currently this optimization is switched off). Currently we have implementation that passes our tests but further investigation is required to estimate and solve performance problems.

**Comment by olegrok** [comment]
> I would be interested in performance testing results.

Here is my modest benchmarks - https://github.com/tarantool/crud/pull/38#issuecomment-725304094
