### ISSUE TITLE
Support vshard's `identification_mode` = `name_as_key`

### ISSUE THREAD

**Issue by Totktonada** [tarantool/crud#403]
It is released in [vshard 0.1.25](https://github.com/tarantool/vshard/releases/tag/0.1.25). See https://github.com/tarantool/doc/issues/3942.

This mode has different `vshard.storage.info()` output: names are there instead of UUIDs.

At least the following crud's code is not ready for that.

https://github.com/tarantool/crud/blob/a897f4c652c6cb4313ed42abd4fc0248d3e45829/crud.lua#L182-L196

**Comment by DifferentialOrange** [comment]
As far as I understand, 0.1.25 with new mode will break the module apart on initialization?

**Comment by Totktonada** [comment]
@DifferentialOrange I don't know, but I hope that the new mode is generally compatible with the old one. Only testing can tell us.
