### ISSUE TITLE
Проблема с crud.count

### ISSUE THREAD

**Issue by AlexTarasevich** [tarantool/crud#418]
Делали запрос crud.count с такими-то параметрами (на видео, которое они скидывали, есть настоящий пример). При перестановке условий получается разный результат, хотя этого не ожидалось. При замене условий с >= на = результат второго запроса больше результата первого, хотя этого тоже не ожидалось.
В принципе, то, чего они не ожидали, действительно не должно быть
В условиях здорового кластера

**Comment by DifferentialOrange** [comment]
На данный момент по предоставленным данным не вышло воспроизвести проблему, были запрошены дополнительные сведения.

**Comment by DifferentialOrange** [comment]
Удалось вопроизвести проблему, в блиажйшее время будет исправление
