### ISSUE TITLE
Add shard group support

### ISSUE THREAD

**Issue by denisb0** [tarantool/crud#44]
If there's custom shard group defined, operations will break at code like `vshard.router.routeall()`. 
It could be fixed by passing shard group name in `opts` argument and using first group in list if it's not provided/not found.

**Comment by Totktonada** [comment]
Vshard group is Cartridge's term. Vshard itself only allows to create several vshard router objects. See also:

* https://github.com/tarantool/doc/issues/2450
* https://github.com/tarantool/doc/issues/2319

My proposal:

* Add `vshard_router` parameter (accepts vshard router object).
* Add `vshard_group` parameter (enabled only if `crud-router` role is started, accepts a vshard group name).

**Comment by Totktonada** [comment]
I'm not right: routers are named in vshard (see the [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_rock/vshard/vshard_router/#lua-function.vshard.router.new)). So we can accept router object and name both in the `vshard_router` parameter.
