### ISSUE TITLE
Allow to pass bucket_id externally

### ISSUE THREAD

**Issue by sharonovd** [tarantool/crud#55]
I have a case when field used to calculate bucket_id is not stored (it is not a part of primary key). Therefore, I'd like to pass bucket_id explicitly to crud.insert and, probably, crud.select forcibly. I am totally ok that crud.get will not work for such cases.

API proposal:
`crud.insert({bucket_id,primary_key,secondary_key,payload}, {external_bucket_id=true})`bucket_id (possibly via opts.external_bucket_id or smth like that)
`crud.select({'secondary_key','=',42},{bucket_id=1})`

**Comment by knazarov** [comment]
I would take a look at #46. 

For integration and performance reasons, the connectors should know exactly the rules of sharding.

Plus, the current rules say that in the absence of an entry in `_sharding_key` space, space is sharded by the primary key. But if you introduce a way to manually push `bucket_id` in queries, you will violate that rule. 

I see the only way to achieve coherency here: to allow specifying `bucket_id` as a sharding key in the `_sharding_key` space. To reduce the amount of magic that happens, we can introduce an optional parameter to `_sharding_key` that is called `hash_function`. To make things easy for the connectors, we will limit the ways in which we allow to specify hash functions.


So we can have it like this:

| space_name | sharding_key | hash_function |
|------------|--------------|---------------|
| account    | {user_id}    | guava         |
| operations | {bucket_id}  | mod           |

`mod` means just take `<field contents>mod<number of buckets>`

**Comment by Totktonada** [comment]
Drimtry's proposal was implemented in #46 and released in crud 0.3.0 (2020-10-26). I'll close this issue to reduce confusion.

Integration with tarantool/ddl is in progress and tracked in #27.

The idea with using bucket_id field itself as sharding key (without extra transformation) is interesting, but we have no such plans ATM.

**Comment by Totktonada** [comment]
It seems, I was not quite right. Using just bucket_id will be possible after #27: one can choose identical function as a sharding function.
