### ISSUE TITLE
Add a method to return connection strings to all routers

### ISSUE THREAD

**Issue by knazarov** [tarantool/crud#57]
Let's add a method called `crud.get_routers()` that will return a list of connection strings to all existing routers. It will allow connectors to request this list and use it to balance requests. This way, the users will have to only put a couple of addresses to the `connect()` call, and the connector will then discover the rest.

**Comment by knazarov** [comment]
It may also be a good idea to add an option called `poll`, that will specify the polling timeout. Calling this function, the clients can be notified as soon as the number of routers changes.

**Comment by NeraverinTarantool** [comment]
Will be implemented as the part of Tarantool 3.0 (closed as duplicate)
