### ISSUE TITLE
Don't create fibers during requests, unless necessary

### ISSUE THREAD

**Issue by knazarov** [tarantool/crud#60]
Currently, as far as I understand, we create fibers for every request, no matter if it's necessary. 

See: https://github.com/tarantool/crud/blob/master/crud/common/call.lua#L88-L94

This is not required when you do a call to single storage. Creating fibers takes time, as well as communication through channels. This is only needed when you do select with map/reduce.

**Comment by mtrempoltsev** [comment]
This is a dubious optimization (especially when compared to a single net hop) requiring more complex code so are you sure if the game is worth the candle?

**Comment by knazarov** [comment]
There are 2 problems:

1. Network latency. You are correct that it won't affect it much.
2. Throughput. Here, unnecessary creation of fibers and interactions through channels will lead to more load on the router, and thus fewer total requests we can process per second.

In general, you have 2 cases:

1. The request goes to a specific node (get/put/upsert, etc). We need to execute them with minimal overhead.
2. Full map-reduce (such as pessimistic selects by secondary keys). Here, we may create fibers as we see fit.

Plus, the problem with the current implementation of single-node operations is that they don't pin vshard buckets. See #59 for details. The only sensible/performant way to fix it is to use vshard callro/callrw functions. And if you use them, there is generally no need to create fibers for that.

**Comment by mtrempoltsev** [comment]
About this thesis:

> Throughput. Here, unnecessary creation of fibers and interactions through channels will lead to more load on the router, and thus fewer total requests we can process per second.

Have you tested both implementations? What difference in performance? If the difference is significant then of course we will do it but I want to remind you about the dangers of premature optimization as far as I know this has not yet been a bottleneck.

> Plus, the problem with the current implementation of single-node operations is that they don't pin vshard buckets.

This will be fixed as part of ticket #59

**Comment by knazarov** [comment]
This issue can now be closed because we fixed it in #58.
