### ISSUE TITLE
Implement select API for simple LEFT JOIN cases

### ISSUE THREAD

**Issue by akudiyar** [tarantool/crud#77]
Use case: data models are often organized in such a way that some aggregates are built using LEFT JOINs (speaking of SQL syntax). Consider two cases: 
1) a customer wants to select all accounts with theirs billing information. Although one way to build such aggregates is de-normalizing the data and saving it in one space, some linked data may be used and changed independently, but linked to one id and therefore shared by the same key. Let's call this "local joins", thus having in mind that the possible "join" will be performed on a storage node with data from one bucket.
2) a customer wants to select all orders in a special status for all accounts with a positive balance. Both spaces have the account_id field but are sharded by a different key. This looks like a more general case, although it can be shrunk to a simple pattern of operations: local joins with filtration + merge of the results with joining the other spaces + final filtration. Of course, in the real world, there will be a lot of optimizations, but a simple "straight" solution will already save a lot of boilerplate code for customers and allow the support for joins in Cartridge connectors.

The proposed API variants:
a) The one proposed by Dmitry -- https://github.com/dimoffon/vshard-cluster-api#joins. Although it looks like a general case, it doesn't specify the kind of join and looks too SQL-ish to my taste. Also implementing the partial cases like the general-purpose API may be both a good way and not so good one.
b) More flexible variation of the syntax:
```
    crud.join('accounts', {{'>', 'balance', 0}}):left_join('orders', 'account_id', {{'=', 'status', 'NEW'}}):select({limit = -10})
```
A more complex case:
```
    crud.join('accounts', {{'>', 'balance', 0}}):left_join('orders', {'accounts.id', 'account_id'}, {{'=', 'status', 'NEW'}}):left_join('payments', {'accounts.id', 'account_id'}, {{'=', 'status', 'CLOSED'}}):select({limit = -10})
```
The set of conditions on the first space will determine the used indexes, as for the select() operation.

**Comment by knazarov** [comment]
The thing with JOINs is they can be done completely on the client. You'd need to wrap the join calls anyway (e.g. you won't use them verbatim). So, what's the need to introduce them to this module?

**Comment by akudiyar** [comment]
Loading all the data for joining to the client via connector for joining them is no way, consider each select from a sharded space returns 1 GB and we have 16 storages, but after joining and filtering on storages we have only several MB of data which are further efficiently merged on router.

**Comment by knazarov** [comment]
To join the data you still need to bring it to the router. So sending it to the client only incurs a 2x overhead. So I see no point in doing this.

**Comment by akudiyar** [comment]
1) We may have local joins and do a normal map-reduce process
2) For the normal select all filtering is done on the router and the connector just proxies the result to the client code. If we do joins on the client, we have to load data directly from the storages, which is harder to implement in connectors and may be less efficient.

**Comment by knazarov** [comment]
- If you have two spaces sharded by a different criteria, then you cannot do a local join
- If you join by a field that is _not_ a sharding key, you also cannot do a local join

In both of those cases, you will have to pull the whole data to the router. No way around that.

The approach you are describing is not as generally useful. You can only benefit in a very specific case.
So you'd be better off with just a stored procedure you send from the client that filters data from 2 spaces.

**Comment by akudiyar** [comment]
Well, registering functions in runtime may solve the problem (connectors can generate them using some declarative info).

But when I need __two__ procedures -- one on the storage (with local joins and/or filtration) and one on the router for the final filtration, how will the function registering look like in this case, will the user have to specify the router/storage attributions for the function?

**Comment by akudiyar** [comment]
One more concern: will runtime function registering require performing extra checks on each call if the function actually exists on the storage? Because new storages may be joined to cluster on runtime and new roles may be deployed.

In case of the CRUD API, it doesn't require any checks and function registration.

**Comment by knazarov** [comment]
As I already told before, you have 2 cases:
1. You can do the join inside the storage nodes, in which case you don't need additional filtering on the router
2. You can't do the join inside the storage nodes, in which case you need to pull the data to the router, and thus you may as well pull it to the client and do the merge there. The overhead will be O(1).

**Comment by akudiyar** [comment]
But what about transferring the data over the network to the client? If we do filtering on the router, we may avoid filling the outgoing bandwidth.

**Comment by knazarov** [comment]
This network overhead will be O(1) because you need to transfer data to the router using the network, right? Transferring this data to the client will only add a constant overhead.

**Comment by kyukhin** [comment]
No plans.

**Comment by artur-barsegyan** [comment]
Я изучил текущие проблемы и потребности с crud. Эта фича не требуется
