### ISSUE TITLE
Tarantool Enterprise referenced in GitLab CI confg

### ISSUE THREAD

**Issue by tsafin** [tarantool/crud#8]
I suspect the reason this has leaked into the CI config, but CRUD API should work with open-source tarantool version, so we should rather get rid of Enterprise specifics here

https://github.com/tarantool/crud/blob/ee09bab1f3a1ed98841196a34175ad89d841a2e1/.gitlab-ci.yml#L19-L26

**Comment by knazarov** [comment]
No, this is by design. We want to test on both enterprise and opensource versions.

**Comment by dokshina** [comment]
I don't see any reasons to leave this issue opened - there is nothing to discuss more.
