### ISSUE TITLE
[4pt] CRUD uses outdated schema from vshard connections

### ISSUE THREAD

**Issue by akudiyar** [tarantool/crud#98]
## Steps to reproduce:

Original issue: see https://github.com/vrogach2020/mdm-sandbox/pull/1

Given the following setup: a Cartridge application + tarantool/crud + tarantool/migrations + integration tests in luatest, an integration test trying to call `crud.insert('test', {...})` fails with error `Failed to insert test, error: Insert: Space "test" doesn't exist`, although the space is initialized from migrations and does exist at the time of call, which is checked beforehand with a code like:
```lua
--wait until migrations are applied
    for _, server in pairs(helper.cluster.servers) do
        --spaces may be created with a slight delay on replicas
        helper.cluster:retrying({ timeout = 1 }, function()
            t.assert_not(server.net_box:eval('return box.space.test == nil'), server.alias)
        end)
    end

    helper.cluster:wait_until_healthy()
```  

CRUD checks the space existence before performing operations on it using internal vshard connections, the simplified code looks like : 

```lua
_, replicaset = next(vshard.router.routeall())
replicaset.master.conn.space[space_name]
```
Investigated by @rosik:
Vshard connection is established before migrations, and until the first insert, there are no other communications. Thus crud uses outdated schema and the request fails.

The suggested W/A is explicitly calling `ping()` for forcing schema update: 
```lua
helper.cluster.main_server.net_box:eval([[
        local vshard = require('vshard')
        for _, r in pairs(vshard.router.routeall()) do
            r.master.conn:ping()
        end
    ]])
```

## Actual result

CRUD may fail to work with spaces if vshard schema in internal connections is outdated, returning a fake "space doesn't exist" error

## Expected result

CRUD doesn't fail to work with spaces when spaces actually exist

## Proposed solution

1. @racktear: do not check for space existence at all.
May lead to errors when attempting to use the space format/metadata.

2. Do not use vshard connections for checking the space existence.
Probably requires the cluster DDL to be implemented

**Comment by knazarov** [comment]
The simplest solution, in this case, maybe to send a ping request through the connection if the space doesn't exist. This request should refresh the schema. After the ping, we may just retry.

**Comment by akudiyar** [comment]
Another case was found by a customer:

1) Having 2 servers, Tarantool storage replica sets consist of 2 nodes, divided between the servers,
2) One of the servers shuts down (reboots),
3) Although replicas on the first server are working after the failover is finished, CRUD continues failing with errors like "...l/appealsdb/.rocks/share/tarantool/crud/common/utils.lua:36: attempt to index field 'space' (a nil value)"

**Comment by mRrvz** [comment]
Space format is not updated in this case:

```lua
rawset(_G, 'add_extra_field', function(name)
    local new_format = box.space.developers:format()
    table.insert(new_format, {name = name, type = 'string', is_nullable = true})
    box.space.developers:format(new_format)
end)

...

local result, err = g.cluster.main_server.net_box:call(
    'crud.insert', {'developers', {1, box.NULL}})
t.assert_equals(err, nil)

helpers.call_on_servers(g.cluster, {'s1-master', 's2-master'}, function(server)
    server.net_box:call('add_extra_field', {'extra_1'})
    server.net_box:call('add_extra_field', {'extra_2'})
end)
    
local result, err = g.cluster.main_server.net_box:call('crud.update',
    {'developers', 1, {{'=', 'extra_2', 'extra_value'}}})
```

If add ``select`` call brefore ``update``:

```lua
local result, err = g.cluster.main_server.net_box:call('crud.select',
    {'developers', nil})
```

space format will be updated.

**Comment by olegrok** [comment]
Seems it's not relevant.

Test in this commit (https://github.com/tarantool/crud/commit/6c304839652be686e76495da297b5a14879efc41) doesn't require any select before update.
